# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True, verbose_name='Título')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('logradouro', models.CharField(max_length=200, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=6, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(max_length=9, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Contato')),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observações')),
                ('lat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('lon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Imóveis',
                'verbose_name': 'Imóvel',
            },
        ),
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criada em')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Imoveis')),
                ('postado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Mensagens')),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
                'verbose_name': 'Mensagem',
            },
        ),
    ]
