# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161109_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='observacoes',
            field=models.TextField(),
        ),
    ]
